### PR TITLE
Kw/local variable name

### LINKED ISSUE #124: Refactor variable / namespace
- namespace
  - encodings.js => specs.js
  - encs.js => encodings.js
  

- local variable

- `gen` => `generate` (for `cp.gen`, `gen.js`)
- encoding => spec
- encs => encodings

- field => fieldDef

### PR DESCRIPTION
**Pull request by kanitw**
Fixes #124 

Rename local variable names, filenames and APIs.

Now 
- spec = the whole encoding (Vega-Lite specification)
- encoding = encoding mapping (`encoding` property in a vega-lite spec)
- fieldDef = an object containing name, type and aggregation function. (This object is a superclass of Vega-Lite's encoding definition)

API change:
- cp.gen.encodings => cp.gen.specs
- cp.gen.encs => cp.gen.encodings

### CODE REVIEW

**Comment by yhoonkim** [comment]
There are several spots that I suspect to change. 
(I'm still finding...)

1. ``distance.js`` ?
```javascript
distance.get = function (colenc1, colenc2) {
  var cols = util.union(vl.keys(colenc1.col), vl.keys(colenc2.col)),
    dist = 0;
...
};
```

2. ``cluster.js`` line 26 ``encoding`` to ``spec``
```javascript
.map(function(cluster) {
    return cluster.sort(function(encoding1, encoding2) {
      // sort each cluster -- have the highest score as 1st item
      return encoding2._info.score - encoding1._info.score;
    });
```

**Comment by kanitw** [comment]
Fixed .. please see the commits for changes.

**Comment by yhoonkim** [comment]
I checked your recent commits. 
I'll inform you after checking all ``src`` files. Around tomorrow afternoon.

**Comment by yhoonkim** [comment]
@kanitw  I checked all files. It looks good to me. 
But I didn't followed the whole context of codes, such as ``vl.xxxx`` things. 
I'm going to catch up these source in 1~2 week.

**Comment by kanitw** [comment]
@yhoonkim Yep. Feel free to ask me if you get confused if anything.   

Feel free to merge this PR as well!

**Comment by domoritz** [comment]
When merged, make a release and merge https://github.com/vega/voyager/pull/225

**Pull request merged**
